title: Ximing的博客
description: (标题的描述)
url: "https://MaiXiming.github.io"
baseurl: ""

locale: zh-CN
timezone: Asia/Shanghai

# Minimal Mistakes 主题（通过 remote_theme 使用）
theme: null
remote_theme: "mmistakes/minimal-mistakes@4.26.1"
minimal_mistakes_skin: "default"

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache

# 站点作者信息（会显示在文章页侧栏等）
author:
  name: Ximing Mai
  avatar: /assets/img/avatar.png
  bio: 简短的自我介绍（可在“关于我”页详细介绍）
  location: 上海

# 社交账号（按需填写）
# social:
#   links:
#     - "https://github.com/MaiXiming"

# 顶部导航使用 _data/navigation.yml
# 如需启用站内搜索，可设为 true（Minimal Mistakes 自带本地搜索）
search: true

# 文章固定链接格式（可按需修改）
permalink: /:categories/:title/

# GitHub 仓库（用于主题的一些链接渲染）
repository: MaiXiming/MaiXiming.github.io

# 评论系统（可选：giscus 示例，后续步骤里会教你如何启用）
comments:
  provider: "giscus"
  giscus:
    repo: "MaiXiming/MaiXiming.github.io"   # 仓库名
    repo_id: "R_kgDOPwCP5g"                   # Giscus生成
    category: "Comments"                     # Discussions分类名
    category_id: "DIC_kwDOPwCP5s4Cvif5"             # Giscus生成
    mapping: "pathname"                      # 文章映射方式
    reactions_enabled: "1"                   # 开启表情反馈
    emit_metadata: "0"
    input_position: "bottom"                 # 评论框位置 bottom / top
    theme: "preferred_color_scheme"
    lang: "zh-CN"

# giscus:
# <script src="https://giscus.app/client.js"
#         data-repo="MaiXiming/MaiXiming.github.io"
#         data-repo-id="R_kgDOPwCP5g"
#         data-category="Announcements"
#         data-category-id="DIC_kwDOPwCP5s4CvifV"
#         data-mapping="pathname"
#         data-strict="0"
#         data-reactions-enabled="1"
#         data-emit-metadata="0"
#         data-input-position="bottom"
#         data-theme="preferred_color_scheme"
#         data-lang="zh-CN"
#         crossorigin="anonymous"
#         async>
# </script>
# comments:
#   provider: "giscus"
#   giscus:
#     repo: "MaiXiming/MaiXiming.github.io"
#     repo_id: ""
#     category: "Announcements"
#     category_id: ""
#     mapping: "pathname"
#     reactions_enabled: "1"
#     emit_metadata: "0"
#     input_position: "bottom"
#     theme: "light"
#     lang: "zh-CN"
